/**:
  ros__parameters:
    video_device: "/dev/video0"
    framerate: 10.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "uyvy"
    image_width: 2880
    image_height: 1860
    camera_name: "test_camera"
    camera_info_url: "package://usb_cam/config/camera_info.yaml"
    image_topic: "/camera_1/image_raw"  # Unique topic for Camera 1

